/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module my_design(clk, rst, in, out);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input in;
  wire in;
  output out;
  wire out;
  wire _0_;
  sky130_fd_sc_hd__inv_2 _1_ (
    .A(rst),
    .Y(_0_)
  );
  sky130_fd_sc_hd__dfrtp_2 _2_ (
    .CLK(clk),
    .D(in),
    .Q(out),
    .RESET_B(_0_)
  );
endmodule
